name: 'Runs dockle'
description: 'Container Image Linter with dockle'
inputs:
  image:
    description: 'image name'
    required: true
  exit-code:
    description: 'exit code when alerts were found'
    required: false
    default: '0'
  exit-level:
    description: 'alert level (INFO, WARN, FATAL)'
    required: false
    default: 'WARN'
  version:
    description: 'dockle version'
    required: false
    default: 'latest'
runs:
  using: 'docker'
  image: 'docker://goodwithtech/dockle:${{ inputs.version }}'
  args:
    - '--exit-code=${{ inputs.exit-code }}'
    - '--exit-level=${{ inputs.exit-level }}'
    - '${{ inputs.image }}'
