name: Scan container vulnerability
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: docker/web/Dockerfile.old

      - name: Set image tag
        id: vars # https://docs.github.com/ja/actions/learn-github-actions/contexts#steps-context
        run: |
          echo '::set-output name=image_tag::docker.io/nemotoy/my-web-app:${{ github.sha }}'

      - name: Print image tag name
        run: |
          echo '${{ steps.vars.outputs.image_tag }}'

      - name: Build an image from Dockerfile
        run: |
          docker build -t ${{ steps.vars.outputs.image_tag }} -f docker/web/Dockerfile.old .

      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@0.0.20
      #   with:
      #     image-ref: 'docker.io/nemotoy/my-web-app:${{ github.sha }}'
      #     format: 'table'
      #     exit-code: '0'
      #     ignore-unfixed: true
      #     vuln-type: 'os,library'
      #     severity: 'CRITICAL,HIGH'

      - name: Run Dockle image scanner
        uses: ./.github/actions/dockle
        with:
          image: '${{ steps.vars.outputs.image_tag }}'
          exit-code: '0'
          exit-level: WARN
