name: Scan container vulnerability
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Lint Dockerfile
      #   uses: hadolint/hadolint-action@v1.6.0
      #   with:
      #     dockerfile: docker/web/Dockerfile.old

      - name: Set image tag
        id: build
        run: |
          echo '::set-output name=image_tag::docker.io/nemotoy/my-web-app:${{ github.sha }}'

      - name: Print image tag name
        run: |
          echo ${{ steps.build.outputs.image_tag }}

      - name: Build an image from Dockerfile
        run: |
          docker build -t ${{ steps.build.outputs.image_tag }} -f docker/web/Dockerfile .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.2.1
        with:
          image-ref: 'docker.io/nemotoy/my-web-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run Dockle image scanner
        uses: nemotoy/dockle-action@v0.0.2
        with:
          image: ${{ steps.build.outputs.image_tag }}
          exit-code: '0'
          exit-level: WARN
          debug: 'true'
          format: 'json'
          output: 'result.json'
      - name: Print result
        run: |
          cat result.json
